name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Generate content
        run: bash ./generate-docs.sh
      - name: Upload docs
        uses: actions/upload-pages-artifact@v1.0.8
        with:
          path: ./generated_docs
      - name: Deploy docs
        id: deployment
        uses: actions/deploy-pages@v2
      - name: Create release
        run: |
         export GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
         gh release create \
            --generate-notes \
            --verify-tag \
            'v1.0.0' \
            './generated_docs/index.html#documentation'
